### ISSUE TITLE
Trying to scrape a page, but errors occur.

### ISSUE THREAD

**Issue by rainer52** [martinsbalodis/web-scraper-chrome-extension#117]
The problem is on pages like that: https://clients.mindbodyonline.com/classic/home?studioid=12023
Basically the Web Scraper does not let you even start selecting the data, which you wish to scrape from the website, I myself have no idea, ehat the problem is, as on other pages the plugin works perfectly, but on pages like that, it simply does not work. Is it a problem on my part or is it a problem on Web Scraper's part?

**Comment by martinsbalodis** [comment]
The problem is in web scraper. The page is loaded within an iframe and Web scraper currently cannot select data from iframes. You should extract data from the iframe url.

https://clients.mindbodyonline.com/classic/mainclass?tg=&vt=&lvl=&stype=&view=&trn=0&page=&catid=&prodid=&date=8%2f28%2f2015&classid=0&prodGroupId=&sSU=&optForwardingLink=&qParam=&justloggedin=&nLgIn=&pMode=0

**Comment by rainer52** [comment]
Thanks, I already figured that out, but I would be extremely grateful, if you could check out, why is it rather impossible to create a table based upon this calendar, also the pagination does not work while trying to move through the weeks.
