### ISSUE TITLE
Zero width no-break space as first character of exported CSV file

### ISSUE THREAD

**Issue by quilicicf** [martinsbalodis/web-scraper-chrome-extension#169]
Hey, 

First of all, thanks a lot for this scraper. It's really useful !

However, I encountered a small bug that may prove very annoying. When extracting the data to CSV, I've got a zero-width no-break space as first character. 
## My use case
- scrape the website
- use a tool to convert the CSV data to JSON (would be awesome to have this built-in)
- feed the JSON to a JS script for processing
### Input CSV

``` csv
﻿time,date,summary
12:20,2016/12/12,'Diner with Toto'
```
### Generated JSON

``` json
[
  {
    "﻿time": "12:20",
    "date": "2016/12/12",
    "summary": "Diner with Toto"
  }
]
```
### Generated JS object

``` js
[
  {
    '﻿time': '12:20',
    date: '2016/12/12',
    summary: 'Diner with Toto'
  }
]
```

Note: due to the no-width character, the JS object wraps the attribute 'time' in quotes. That's what got me understanding the bug.
### Effect

Calling `object.time` does not work. To get the time in the object, one has to call `object['﻿time']` (WITH the zero-width character at the begining).
## Reproduced on
- **OS:** Ubuntu 16.04
- **Browser:** Version 53.0.2785.116 (64-bit)
- **Web scraper:** 0.2.0.10

**Comment by martinsbalodis** [comment]
The first character in the CSV file is an utf-8 BOM character. It is there so that MS excel knows that the file encoding is in utf-8 and not in ascii. I cannot really remove it. You'll have to work around it somehow.

**Comment by quilicicf** [comment]
That's weird because when copying the invisible character in [unicode lookup](http://unicodelookup.com/) it told me it was the character `zero width no-break space (0177377	65279	0xFEFF	&#65279;)` as if the BOM header was broken somehow. 

Anyway, now that I know it I can just remove it manually but some other users may get frustrated. A solution would be to detect the OS and write the BOM header only for Windows. 

I'll let you decide what you want to do about that.

**Comment by alexandramartinez** [comment]
I have an issue with this too :(

After I export the CSV file, I want to be able to read it from a MuleSoft app. The thing is that with this BOM character, it does not read the header correctly and generates a null value for all this column. My workarounds are to 1) remove the character manually from each CSV, or 2) change my app to **include** this character at the beginning of the header (which is really annoying because later I have to transform to JSON and the data appears with this).

I'm not asking to change it directly on this project, but it would be really nice if you'd help me figure out how could I resolve this problem without having to perform one of these workarounds. I have to export 500+ CSV files, and changing them manually would not be good for me :'(

Any response would be awesome. Thank you!!

**Comment by quilicicf** [comment]
Well @alexandramartinez I wrote a (gulp) script to remove the unwanted character from my CSVs, I can open-source it if you're interested.
It's hacky but should get you going.

**Comment by alexandramartinez** [comment]
@quilicicf it would be really nice! thank you!

**Comment by quilicicf** [comment]
@alexandramartinez 
https://github.com/quilicicf/Zero_Width_Spaces_Remover 
Add an issue if something's amiss :)

**Comment by alexandramartinez** [comment]
@quilicicf thank you so much!!
